### ISSUE TITLE
Unknown option: .babelrc.presets

### ISSUE THREAD

**Issue by mauricioklein** [rus0000/wordcloud#1]
I'm getting this error when building/running the project:

```bash
Module build failed: ReferenceError: [BABEL] /home/klein/workspace/pr-cloud/components/wordcloud/test/wordcloud.test.js: Unknown option: /home/klein/workspace/pr-cloud/.babelrc.presets
    at Logger.error (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/home/klein/workspace/pr-cloud/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/home/klein/workspace/pr-cloud/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/home/klein/workspace/pr-cloud/node_modules/babel-loader/index.js:71:12)
```

Already installed the babel presets, but the error persists:

```bash
npm install --save-dev babel-cli babel-preset-react babel-preset-es2015
```

**Comment by mauricioklein** [comment]
Nevermind, I think it was something with my clone.
Just re-cloned the project and everything is running well.
Sorry about the mistake.
